apiVersion: v1
kind: Service
metadata:
  name: department-spring-boot-docker
spec:
  selector:
    app: department-spring-boot-docker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
 